development:
  host: localhost
  database: cantaloupe
  username: postgres
  password: "123123"

test:
  host: localhost
  database: cantaloupe_test
  username: postgres
  password: "123123"

production:
  host: localhost
  database: cantaloupe
  username: postgres
  password: "123123"
