development:
  host: localhost
  database: cantaloupe
  username: postgress
  password: ""

test:
  host: localhost
  database: cantaloupe_test
  username: postgress
  password: ""

production:
  host: localhost
  database: cantaloupe
  username: postgress
  password: ""
